### ISSUE TITLE
view by issue

### ISSUE THREAD

**Issue by jaagameister** [Jaaga/videovol#9]

**Comment by thengugi** [comment]
hey guyz! hope you all had a nice weekend.......on approaching our first
milestone, we agreed to have the pages ready and early this week. I have
come up with a simple index.php page which you can check out on git
https://github.com/thengugi/videovol.git.
Fell free to air your opinion and make changes too.
Wish you all a happy coding week.

**Comment by thengugi** [comment]
ngugi ngugi sent you an invitation

Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

```
Accept invitation
```

https://twitter.com/i/ec1cb5a8-eb97-4b0a-be4c-3f4fe458218a

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Unsubscribe: https://twitter.com/i/o?t=1&iid=6221548dfc7440c688bfe95c21976f4d&uid=0&c=IuVwbCB3dgEU7vVQ7lwUmDbVavu36NJptga7bIVBFDEDHr1%2BmQKy3ZZ50qHNnq1bVAgzgRaMoNHl2SKrmr9AIp8uPRNwEIoqLcJC5NA7TeftpVkLcM2rKA%3D%3D&nid=9+26

Need help?
https://support.twitter.com

**Comment by thengugi** [comment]
Hi Jaaga/videovol,

I&#39;d like to add you to my professional network on LinkedIn.
- Peter

Accept: http://www.linkedin.com/blink?simpleRedirect=e3gQd38Me3kSc38Oe3wPc3wVdjR4imVLqnhxt6BSrCACu3BOlmBalDwZumlbp6lOomxP9DhPpnlDnSlQqnpKqjRHpipxt6cJpnhFtCVFbnhPpnlDbmNJpjRDrCBHoS5Ot2pBt6BSrABDpl9BsD0ZoioMdyROqT9Ns30TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=0MdyROqT9Ns30TqiROu69Ad3RAqmkCc6paszsJen1ytP8PdORSllsRmn4Npj16l6BDe5Bhi6pdpBdHmmJJdAVRi4dlhS9koDpOm4FlsApHd3tlqCVIs5lbtzgOs55cmmdIhCtUi7pKkRpmi3BqtktvonxHhPlEqz51imNAjndziA8NgjgRenxlj3pNm7dQcT9iknoQk3hjlz1al39ckT5vplF3oS8StBl1gk5hhAhLnPARlkJqoAxhgjRAqmZI9DhPpnlDnSlQqnpKqjRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2oMdyROqT9Ns30TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5980388250278195200_500&amp;markAsRead=This email was intended for Jaaga/videovol Jaaga/videovol. Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9DhPpnlDnSlQqnpKqjRHpipIsBlBoSBSsCljsClJrThPtmcZoioMdyROqT9Ns30TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thengugi** [comment]
Peter Ngugi would like to connect on LinkedIn. How would you like to respond?

Accept: http://www.linkedin.com/blink?simpleRedirect=e3gQd38Me3kSc38Oe3wPc3wVdjR4imVLqnhxt6BSrCACu3BOlmBalDwZumlbp6lOomxP9zANnT1UplZSrCAZqSkCsClArCBJpn8Jt71BoSdxbm8JpTpKqlZJrmZzbmNJpjRDrCBHoS5Ot2pBt6BSrABDpl9BsD0ZoipHdyRGozlyc3cTqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

View Peter Ngugi&#39;s profile: http://www.linkedin.com/blink?simpleRedirect=3ANnT1UplZSrCAZqSkCsClArCBJpn8Jt71BoSdxbm8JpTpKqlZJrmZzbmNJpjRDrCBHoS5Ot2pSs6UZt2pHdyRGozlyc3cTqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBcPwMdjgQdyQPdzsPc3lBd64Uc6gRcmcPdPtzdCcMpj4Oe3gRemgPcCgSoCoNd68TbjcRejsTc3cPbmB2cylVr71BszRIqm5JpioMdz0MczRAqioUd3gQcz0UdjoMcz8Ue3cMe3ARfmhFpOoVclZMu6lvtCVFfmJB9C9RsSVRbmoJoS9BrlZJrmZzbmNJpjRDrCBHoS5Ot2pLrSsZt2pHdyRGozlyc3cTqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: http://www.linkedin.com/blink?simpleRedirect=6ISbmFydm8McPtFbn9UoCgQfmhFpippr4lPp5Zzj75IjQ92k6Jzuzxze4ENd39Sj4FPq75zhB9Ii55FrB1AiCBHcBdGukRKp71zondvr2RUgR9ylnBqrkBGljxKrQFQd6FfgmNfh4lmjklvol9Jm4tKtn5ihl1hh75CtBx7r3x6gQlngQERnRxQoARqk3ljhyRPqQtzeltecllpdS9yskZlcn1BsQdTlk51gk5RjPsQdAEQtRYNhl51fmhFrSMCej5vs7xBnTpKqjRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2pHdyRGozlyc3cTqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5980388250278195200_500&amp;markAsRead= Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Cej5vs7xBnTpKqjRHpipIsBlBoSBSsCljsClJrThPtmcZoipHdyRGozlyc3cTqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by thengugi** [comment]
Peter Ngugi would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=e3gQd38Me3kSc38Oe3wPc3wVdjR4imVLqnhxt6BSrCACu3BOlmBalDwZumlbp6lOomxP9zANnT1UplZSrCAZqSkCsClArCBJpn8Jt71BoSdxbm8JpTpKqlZJrmZzbmNJpjRDrCBHoS5Ot2pBt6BSrABDpl9BsD0ZoipCciRKtnFVsm8TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

View Peter Ngugi&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3ANnT1UplZSrCAZqSkCsClArCBJpn8Jt71BoSdxbm8JpTpKqlZJrmZzbmNJpjRDrCBHoS5Ot2pSs6UZt2pCciRKtnFVsm8TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBcPwMdjgQdyQPdzsPc3lBd64Uc6gRcmcPdPtzdCcMpj4Oe3gRemgPcCgSoCoNd68TbjcRejsTc3cPbmB2cylVr71BszRIqm5JpioMdz0MczRAqioUd3gQcz0UdjoMcz8Ue3cMe3ARfmhFpOoVclZMu6lvtCVFfmJB9C9RsSVRbmoJoS9BrlZJrmZzbmNJpjRDrCBHoS5Ot2pLrSsZt2pCciRKtnFVsm8TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6oNbmVRuDBNoztFbn9UoCgQfmhFpip5rlFyrBtpd4EQrChekCp2hSkVknlvk79KhSRIuk9qlTBAcRFhgSBoc6NxsCRWkAR1sD5zkAJ6kjBhtkhUgAZ5tjBGblhhqSANk4JAulFDe6YOrCVgjmtAbmthhPsOgD1qh4B9rQ9KcAQOc4QTiCB9jB9qhzwPbmJWbl54kn91h4JKrktOsmFze6tycTBIjmBTlk51gntCq3dFgzxFhRZohB51fmhFrSMCej5vs7xBnTpKqjRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2pCciRKtnFVsm8TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5980388250278195200_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Cej5vs7xBnTpKqjRHpipIsBlBoSBSsCljsClJrThPtmcZoipCciRKtnFVsm8TqiROu69Ad3RBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5980388250278195200_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
